function Hd = G_rcos
%G_RCOS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.3 and DSP System Toolbox 9.5.
% Generated on: 25-May-2018 20:54:28

% FIR Window Raised-cosine filter designed using the FIRRCOS function.

% All frequency values are normalized to 1.

N    = 30;         % Order
Fc   = 0.5;        % Cutoff Frequency
TM   = 'Rolloff';  % Transition Mode
R    = 0.0625;     % Rolloff
DT   = 'sqrt';     % Design Type
Beta = 0.5;        % Window Parameter

% Create the window vector for the design algorithm.
win = kaiser(N+1, Beta);

% Calculate the coefficients using the FIR1 function.
b  = firrcos(N, Fc, R, 2, TM, DT, [], win);
Hd = dfilt.dffir(b);

% [EOF]
